# Generated by Django 5.2.7 on 2025-11-06 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trigger',
            name='workspace',
        ),
        migrations.AddField(
            model_name='trigger',
            name='automation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='automations.automation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trigger',
            name='trigger_key',
            field=models.CharField(default='ha', max_length=100),
            preserve_default=False,
        ),
    ]
