# Generated by Django 5.2.7 on 2025-11-06 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0002_remove_trigger_workspace_trigger_automation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='integration',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='automations.integration'),
            preserve_default=False,
        ),
    ]
