# Generated by Django 5.2.7 on 2025-12-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0005_trigger_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trigger',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('tested', 'Tested'), ('draft', 'Draft')], default='draft', max_length=20),
        ),
    ]
