# Generated by Django 5.2.7 on 2025-12-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0006_alter_trigger_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='last_tested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
