# Generated by Django 5.2.7 on 2025-12-25 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0007_trigger_last_tested_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='last_run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
