# Generated by Django 5.2.7 on 2025-12-25 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0008_trigger_last_run_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trigger',
            name='integration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automations.integration'),
        ),
    ]
