# Generated by Django 5.2.7 on 2025-12-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0009_alter_trigger_integration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trigger',
            name='config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
