# Generated by Django 5.2.7 on 2026-01-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0011_eventrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventrecord',
            name='service',
        ),
        migrations.AddField(
            model_name='eventrecord',
            name='external_id',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventrecord',
            name='integration',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventrecord',
            name='trigger',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
