# Generated by Django 5.2.7 on 2026-01-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0012_remove_eventrecord_service_eventrecord_external_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrecord',
            name='event_id',
            field=models.CharField(db_index=True, default='', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
