# Generated by Django 5.2.7 on 2026-01-27 11:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0013_eventrecord_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrecord',
            name='recorded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventrecord',
            name='occurred_at',
            field=models.DateTimeField(),
        ),
    ]
