# Generated by Django 5.2.7 on 2026-01-28 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0014_eventrecord_recorded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrecord',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='eventrecord',
            constraint=models.UniqueConstraint(fields=('integration', 'external_id'), name='unique_event_from_source'),
        ),
    ]
