# Generated by Django 5.2.7 on 2026-04-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0015_eventrecord_processed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
