# Generated by Django 5.2.7 on 2026-04-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0016_execution_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='automation',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
