# Generated by Django 5.2.7 on 2026-05-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0017_automation_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='step',
            name='status',
            field=models.CharField(default='draft'),
        ),
        migrations.AlterField(
            model_name='step',
            name='kind',
            field=models.CharField(choices=[('action', 'Action'), ('condition', 'Condition')], default='action', max_length=20),
        ),
    ]
