# Generated by Django 5.2.7 on 2026-05-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0018_alter_automation_options_step_status_alter_step_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='action_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
