# Generated by Django 5.2.7 on 2026-05-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0020_alter_trigger_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='automation',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
