# Generated by Django 5.2.7 on 2026-05-29 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0021_automation_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trigger',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('ready', 'Ready'), ('draft', 'Draft')], default='draft', max_length=20),
        ),
    ]
