# Generated by Django 5.2.7 on 2026-05-29 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0022_alter_trigger_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automation',
            name='trigger',
        ),
    ]
