# Generated by Django 5.2.7 on 2026-05-29 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0023_remove_automation_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trigger',
            name='automation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trigger', to='automations.automation'),
        ),
    ]
