# Generated by Django 5.2.7 on 2026-06-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0024_alter_trigger_automation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='connection',
            name='secrets',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
